[package]
name = "bittorrent"
version = "0.1.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
bendy = "0.3.2"
chrono = "0.4.11"
thiserror = "1.0.20"
